/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccountsApi,
  TransactionsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrexTransactionsCustom } from "./client-custom";

export class BrexTransactions extends BrexTransactionsCustom {
  readonly accounts: AccountsApi;
  readonly transactions: TransactionsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.accounts = new AccountsApi(configuration);
    this.transactions = new TransactionsApi(configuration);
  }

}
