/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardAccountCurrentBalance } from './card-account-current-balance';
import { StatementPeriod } from './statement-period';
import { Status } from './status';

/**
 * 
 * @export
 * @interface CardAccount
 */
export interface CardAccount {
    /**
     * ID of the card account
     * @type {string}
     * @memberof CardAccount
     */
    'id': string;
    /**
     * 
     * @type {Status}
     * @memberof CardAccount
     */
    'status'?: Status;
    /**
     * 
     * @type {CardAccountCurrentBalance}
     * @memberof CardAccount
     */
    'current_balance'?: CardAccountCurrentBalance;
    /**
     * 
     * @type {CardAccountCurrentBalance}
     * @memberof CardAccount
     */
    'available_balance'?: CardAccountCurrentBalance;
    /**
     * 
     * @type {CardAccountCurrentBalance}
     * @memberof CardAccount
     */
    'account_limit'?: CardAccountCurrentBalance;
    /**
     * 
     * @type {StatementPeriod}
     * @memberof CardAccount
     */
    'current_statement_period': StatementPeriod;
}

