/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type CardTransactionType = 'PURCHASE' | 'REFUND' | 'CHARGEBACK' | 'REWARDS_CREDIT' | 'COLLECTION' | 'BNPL_FEE'

