/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Merchant } from './merchant';

/**
 * 
 * @export
 * @interface CardTransactionMerchant
 */
export interface CardTransactionMerchant {
    /**
     * Merchant descriptor
     * @type {string}
     * @memberof CardTransactionMerchant
     */
    'raw_descriptor': string;
    /**
     * https://en.wikipedia.org/wiki/Merchant_category_code
     * @type {string}
     * @memberof CardTransactionMerchant
     */
    'mcc': string;
}

