/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * 
 * @export
 * @interface CardAccountCurrentBalance
 */
export interface CardAccountCurrentBalance {
    /**
     * The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
     * @type {number}
     * @memberof CardAccountCurrentBalance
     */
    'amount'?: number;
    /**
     * The type of currency, in ISO 4217 format. Default to USD if not specified
     * @type {string}
     * @memberof CardAccountCurrentBalance
     */
    'currency'?: string | null;
}

