/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { Status } from './status';

/**
 * 
 * @export
 * @interface CashAccount
 */
export interface CashAccount {
    /**
     * ID of the cash account
     * @type {string}
     * @memberof CashAccount
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CashAccount
     */
    'name': string;
    /**
     * 
     * @type {Status}
     * @memberof CashAccount
     */
    'status'?: Status;
    /**
     * 
     * @type {Money}
     * @memberof CashAccount
     */
    'current_balance': Money;
    /**
     * 
     * @type {Money}
     * @memberof CashAccount
     */
    'available_balance': Money;
    /**
     * 
     * @type {string}
     * @memberof CashAccount
     */
    'account_number': string;
    /**
     * 
     * @type {string}
     * @memberof CashAccount
     */
    'routing_number': string;
    /**
     * Whether or not this account is the primary account. There will always be only one primary account.
     * @type {boolean}
     * @memberof CashAccount
     */
    'primary': boolean;
}

