/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardAccountCurrentBalance } from './card-account-current-balance';
import { CashTransactionType } from './cash-transaction-type';

/**
 * 
 * @export
 * @interface CashTransaction
 */
export interface CashTransaction {
    /**
     * Description of the transaction
     * @type {string}
     * @memberof CashTransaction
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CashTransaction
     */
    'id': string;
    /**
     * 
     * @type {CardAccountCurrentBalance}
     * @memberof CashTransaction
     */
    'amount'?: CardAccountCurrentBalance;
    /**
     * ISO 8601 date of when the payment is initiated
     * @type {string}
     * @memberof CashTransaction
     */
    'initiated_at_date': string;
    /**
     * ISO 8601 date of when the payment is posted
     * @type {string}
     * @memberof CashTransaction
     */
    'posted_at_date': string;
    /**
     * 
     * @type {CashTransactionType}
     * @memberof CashTransaction
     */
    'type'?: CashTransactionType;
    /**
     * Transfer ID to fetch additional metadata about the transaction using `https://developer.brex.com/openapi/payments_api/#operation/getTransfersById`
     * @type {string}
     * @memberof CashTransaction
     */
    'transfer_id'?: string | null;
}

