/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type CashTransactionType = 'PAYMENT' | 'DIVIDEND' | 'FEE' | 'ADJUSTMENT' | 'INTEREST' | 'CARD_COLLECTION' | 'REWARDS_REDEMPTION' | 'RECEIVABLES_OFFERS_ADVANCE' | 'FBO_TRANSFER' | 'RECEIVABLES_OFFERS_REPAYMENT' | 'RECEIVABLES_OFFERS_COLLECTION' | 'BREX_OPERATIONAL_TRANSFER' | 'INTRA_CUSTOMER_ACCOUNT_BOOK_TRANSFER' | 'BOOK_TRANSFER' | 'CRYPTO_BRIDGE'

