/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700. 
 * @export
 * @interface Money
 */
export interface Money {
    /**
     * The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
     * @type {number}
     * @memberof Money
     */
    'amount'?: number;
    /**
     * The type of currency, in ISO 4217 format. Default to USD if not specified
     * @type {string}
     * @memberof Money
     */
    'currency'?: string | null;
}

