/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Statement } from './statement';

/**
 * 
 * @export
 * @interface PageStatement
 */
export interface PageStatement {
    /**
     * 
     * @type {string}
     * @memberof PageStatement
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<Statement>}
     * @memberof PageStatement
     */
    'items': Array<Statement>;
}

