/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashAccount } from './cash-account';

/**
 * 
 * @export
 * @interface PageCashAccount
 */
export interface PageCashAccount {
    /**
     * 
     * @type {string}
     * @memberof PageCashAccount
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<CashAccount>}
     * @memberof PageCashAccount
     */
    'items': Array<CashAccount>;
}

