/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashTransaction } from './cash-transaction';

/**
 * 
 * @export
 * @interface PageCashTransaction
 */
export interface PageCashTransaction {
    /**
     * 
     * @type {string}
     * @memberof PageCashTransaction
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<CashTransaction>}
     * @memberof PageCashTransaction
     */
    'items': Array<CashTransaction>;
}

