/*
Transactions API


The transactions API lets you view your transactions, accounts, and statements.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardTransaction } from './card-transaction';

/**
 * 
 * @export
 * @interface PageCardTransaction
 */
export interface PageCardTransaction {
    /**
     * 
     * @type {string}
     * @memberof PageCardTransaction
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<CardTransaction>}
     * @memberof PageCardTransaction
     */
    'items': Array<CardTransaction>;
}

